name: "Build and Release Docker Image"
description: "Action para build e release usando docker buildx e script Python"
inputs:
  # ci-registry:
  #   description: "Registry Docker"
  #   required: true
  # ci-registry-image:
  #   description: "Imagem Docker"
  #   required: true
  # ci-registry-user:
  #   description: "Usuário para login no registry"
  #   required: true
  # ci-registry-password:
  #   description: "Senha para login no registry"
  #   required: true
  branch_name:
    description: "Nome da branch atual"
    required: true
  github_token:
    description: "Toke github"
    required: true
  github_owner:
    description: "dono da bola"
    required: true
  github_repo_name:
    description: "repo name"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "package"
  color: "blue"
